export const ApiCodes = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_FETCHED: "ORDER_FETCHED",
  ORDERS_FETCHED: "ORDERS_FETCHED",
  ORDER_DELETED: "ORDER_DELETED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  DUPLICATE_BLOCKED: "DUPLICATE_BLOCKED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ApiCode = (typeof ApiCodes)[keyof typeof ApiCodes];
